[package]
name    = "atlas-engine"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
iced.workspace                 = true
ropey.workspace                = true
unicode-segmentation.workspace = true
