[package]
name    = "atlas"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "atlas"
path = "main.rs"

[dependencies]
iced.workspace     = true
atlas-widgets.path = "../atlas-widgets"
atlas-engine.path  = "../atlas-engine"
atlas-keys.path    = "../atlas-keys"
